package com.userservice.dto.response;

import lombok.*;

/**
 * ==========================================================
 * DTO Name : UserRegistrationResponse
 *
 * Description:
 * Returned after successful User Registration.
 * ==========================================================
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserRegistrationResponse {

    /**
     * User ID
     */
    private Long id;

    /**
     * User Email
     */
    private String email;

    /**
     * User First Name
     */
    private String firstName;

    /**
     * User Last Name
     */
    private String lastName;

    /**
     * Success Message
     */
    private String message;

}



















































































































































































































































































































































/*
package com.userservice.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

*/
/**
 * Response DTO returned after successful user registration.
 *//*

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserRegistrationResponse {

    */
/**
     * User ID generated by the database.
     *//*

    private Long id;

    */
/**
     * Username of the registered user.
     *//*

   // private String userName;

    */
/**
     * Registered email address.
     *//*

    private String email;

    */
/**
     * User's first name.
     *//*

    private String firstName;

    */
/**
     * User's last name.
     *//*

    private String lastName;

    */
/**
     * Success message.
     *//*

    private String message;

}*/
